"""Seed script for demo leads.

Usage:
    python -m app.seed              # skip if leads already exist
    python -m app.seed --reset      # clear existing leads and reseed
"""

import argparse

from app.core.database import Base, SessionLocal, engine
from app.models.lead import Lead, LeadQualificationHistory, LeadScoreHistory
from app.routers.leads import apply_scoring
from app.services.scoring_service import score_lead

SAMPLE_LEADS = [
    {
        "first_name": "Sarah",
        "last_name": "Chen",
        "email": "sarah.chen@acmecorp.com",
        "phone": "+1-415-555-0134",
        "company": "Acme Corp",
        "job_title": "VP of Sales",
        "industry": "Software",
        "company_size": 1200,
        "source": "Webinar",
        "email_opens": 12,
        "website_visits": 24,
        "content_downloads": 6,
        "page_visits": 45,
        "time_on_site": 18,
        "form_submissions": 4,
        "budget": "High",
        "authority": "C-Level",
        "pain_points": "Manual lead routing slows our sales cycle; reps waste time on unqualified leads.",
        "timeline": "Immediate",
        "status": "qualified",
    },
    {
        "first_name": "James",
        "last_name": "Okoro",
        "email": "james.okoro@northwindtech.com",
        "phone": "+1-312-555-0178",
        "company": "Northwind Tech",
        "job_title": "Director of Marketing",
        "industry": "Technology",
        "company_size": 350,
        "source": "LinkedIn",
        "email_opens": 8,
        "website_visits": 15,
        "content_downloads": 4,
        "page_visits": 22,
        "time_on_site": 9,
        "form_submissions": 3,
        "budget": "Medium",
        "authority": "Director",
        "pain_points": "Low conversion from marketing-qualified leads.",
        "timeline": "1-3mo",
        "status": "new",
    },
    {
        "first_name": "Priya",
        "last_name": "Patel",
        "email": "priya.patel@globexsolutions.io",
        "phone": "+1-646-555-0119",
        "company": "Globex Solutions",
        "job_title": "Sales Operations Manager",
        "industry": "IT Services",
        "company_size": 180,
        "source": "Website",
        "email_opens": 4,
        "website_visits": 6,
        "content_downloads": 2,
        "page_visits": 9,
        "time_on_site": 4,
        "form_submissions": 1,
        "budget": "Medium",
        "authority": "Manager",
        "pain_points": "",
        "timeline": "3-6mo",
        "status": "new",
    },
    {
        "first_name": "Tom",
        "last_name": "Beckett",
        "email": "tom.beckett@umbrella-labs.com",
        "phone": "",
        "company": "Umbrella Labs",
        "job_title": "SDR",
        "industry": "Biotech",
        "company_size": 45,
        "source": "Referral",
        "email_opens": 1,
        "website_visits": 2,
        "content_downloads": 0,
        "page_visits": 3,
        "time_on_site": 1,
        "form_submissions": 0,
        "budget": "Low",
        "authority": "Manager",
        "pain_points": "",
        "timeline": "",
        "status": "new",
    },
    {
        "first_name": "Ana",
        "last_name": "Rodriguez",
        "email": "ana.rodriguez@finsecure.com",
        "phone": "+1-305-555-0162",
        "company": "FinSecure",
        "job_title": "Chief Revenue Officer",
        "industry": "Finance",
        "company_size": 2500,
        "source": "Conference",
        "email_opens": 20,
        "website_visits": 30,
        "content_downloads": 9,
        "page_visits": 60,
        "time_on_site": 25,
        "form_submissions": 5,
        "budget": "High",
        "authority": "C-Level",
        "pain_points": "No unified revenue intelligence; forecasting is manual and inaccurate.",
        "timeline": "Immediate",
        "status": "qualified",
    },
    {
        "first_name": "Mike",
        "last_name": "Liu",
        "email": "mike.liu@stratopoint.com",
        "phone": "+1-206-555-0150",
        "company": "StratoPoint",
        "job_title": "Operations Lead",
        "industry": "Logistics",
        "company_size": 90,
        "source": "Content",
        "email_opens": 3,
        "website_visits": 5,
        "content_downloads": 1,
        "page_visits": 7,
        "time_on_site": 3,
        "form_submissions": 1,
        "budget": "",
        "authority": "",
        "pain_points": "Struggling to prioritize inbound leads.",
        "timeline": "3-6mo",
        "status": "new",
    },
    {
        "first_name": "Emma",
        "last_name": "Thompson",
        "email": "emma.thompson@northwindconsulting.com",
        "phone": "+1-617-555-0188",
        "company": "Northwind Consulting",
        "job_title": "Sales Manager",
        "industry": "Consulting",
        "company_size": 150,
        "source": "LinkedIn",
        "email_opens": 6,
        "website_visits": 8,
        "content_downloads": 3,
        "page_visits": 12,
        "time_on_site": 3,
        "form_submissions": 2,
        "budget": "Medium",
        "authority": "Manager",
        "pain_points": "No visibility into which leads deserve rep time.",
        "timeline": "1-3mo",
        "status": "new",
    },
    {
        "first_name": "Daniel",
        "last_name": "Wright",
        "email": "daniel.wright@techstart.com",
        "phone": "+1-512-555-0144",
        "company": "TechStart",
        "job_title": "Sales Director",
        "industry": "Software",
        "company_size": 80,
        "source": "Webinar",
        "email_opens": 4,
        "website_visits": 6,
        "content_downloads": 2,
        "page_visits": 8,
        "time_on_site": 4,
        "form_submissions": 1,
        "budget": "High",
        "authority": "Director",
        "pain_points": "Reps are overwhelmed; no scoring system in place.",
        "timeline": "1-3mo",
        "status": "contacted",
    },
    {
        "first_name": "Laura",
        "last_name": "Bennett",
        "email": "laura.bennett@finedge.com",
        "phone": "+1-212-555-0129",
        "company": "FinEdge",
        "job_title": "VP of Finance",
        "industry": "Finance",
        "company_size": 600,
        "source": "Conference",
        "email_opens": 3,
        "website_visits": 5,
        "content_downloads": 1,
        "page_visits": 8,
        "time_on_site": 4,
        "form_submissions": 1,
        "budget": "Medium",
        "authority": "C-Level",
        "pain_points": "Forecasting is manual and error-prone across 3 teams.",
        "timeline": "Immediate",
        "status": "qualified",
    },
    {
        "first_name": "Chris",
        "last_name": "Evans",
        "email": "chris.evans@novamfg.com",
        "phone": "+1-313-555-0166",
        "company": "Nova Manufacturing",
        "job_title": "Procurement Manager",
        "industry": "Manufacturing",
        "company_size": 2000,
        "source": "Trade Show",
        "email_opens": 4,
        "website_visits": 7,
        "content_downloads": 2,
        "page_visits": 10,
        "time_on_site": 3,
        "form_submissions": 2,
        "budget": "Medium",
        "authority": "Manager",
        "pain_points": "Long sales cycles; wants better lead prioritization.",
        "timeline": "1-3mo",
        "status": "new",
    },
    {
        "first_name": "Grace",
        "last_name": "Liu",
        "email": "grace.liu@brightpathlearning.com",
        "phone": "+1-415-555-0171",
        "company": "BrightPath Learning",
        "job_title": "Marketing Coordinator",
        "industry": "Education",
        "company_size": 60,
        "source": "Content",
        "email_opens": 2,
        "website_visits": 4,
        "content_downloads": 1,
        "page_visits": 5,
        "time_on_site": 2,
        "form_submissions": 1,
        "budget": "Low",
        "authority": "",
        "pain_points": "Evaluating sales tools to support team growth.",
        "timeline": "3-6mo",
        "status": "new",
    },
    {
        "first_name": "Ethan",
        "last_name": "Brooks",
        "email": "ethan.brooks@greenleafenergy.com",
        "phone": "+1-303-555-0135",
        "company": "GreenLeaf Energy",
        "job_title": "Business Development Manager",
        "industry": "Energy",
        "company_size": 250,
        "source": "Website",
        "email_opens": 3,
        "website_visits": 4,
        "content_downloads": 1,
        "page_visits": 6,
        "time_on_site": 2,
        "form_submissions": 1,
        "budget": "Medium",
        "authority": "Manager",
        "pain_points": "Wants better reporting on sales pipeline.",
        "timeline": "3-6mo",
        "status": "new",
    },
    {
        "first_name": "Hannah",
        "last_name": "Miller",
        "email": "hannah.miller@craftandco.com",
        "phone": "",
        "company": "Craft & Co",
        "job_title": "Owner",
        "industry": "Retail",
        "company_size": 25,
        "source": "Referral",
        "email_opens": 0,
        "website_visits": 1,
        "content_downloads": 0,
        "page_visits": 2,
        "time_on_site": 1,
        "form_submissions": 0,
        "budget": "Low",
        "authority": "",
        "pain_points": "",
        "timeline": "",
        "status": "new",
    },
    {
        "first_name": "Oliver",
        "last_name": "Brown",
        "email": "oliver.brown@birchwooddental.com",
        "phone": "+1-503-555-0193",
        "company": "Birchwood Dental",
        "job_title": "Office Manager",
        "industry": "Healthcare",
        "company_size": 12,
        "source": "Website",
        "email_opens": 1,
        "website_visits": 3,
        "content_downloads": 0,
        "page_visits": 3,
        "time_on_site": 1,
        "form_submissions": 0,
        "budget": "Low",
        "authority": "Manager",
        "pain_points": "",
        "timeline": "3-6mo",
        "status": "new",
    },
    {
        "first_name": "Isabella",
        "last_name": "Costa",
        "email": "isabella.costa@medisight.com",
        "phone": "+1-917-555-0115",
        "company": "Medisight",
        "job_title": "VP of Sales",
        "industry": "Healthcare",
        "company_size": 800,
        "source": "Webinar",
        "email_opens": 9,
        "website_visits": 15,
        "content_downloads": 5,
        "page_visits": 25,
        "time_on_site": 8,
        "form_submissions": 4,
        "budget": "High",
        "authority": "C-Level",
        "pain_points": "Sales team manually sorts hundreds of inbound leads weekly.",
        "timeline": "Immediate",
        "status": "qualified",
    },
    {
        "first_name": "Noah",
        "last_name": "Williams",
        "email": "noah.williams@cloudnex.com",
        "phone": "+1-425-555-0182",
        "company": "CloudNex",
        "job_title": "CTO",
        "industry": "Software",
        "company_size": 450,
        "source": "LinkedIn",
        "email_opens": 6,
        "website_visits": 10,
        "content_downloads": 3,
        "page_visits": 12,
        "time_on_site": 5,
        "form_submissions": 3,
        "budget": "High",
        "authority": "C-Level",
        "pain_points": "Revenue intelligence is fragmented across spreadsheets.",
        "timeline": "1-3mo",
        "status": "contacted",
    },
]


def seed(reset: bool = False) -> None:
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        existing = db.query(Lead).count()
        if reset:
            db.query(LeadQualificationHistory).delete()
            db.query(LeadScoreHistory).delete()
            db.query(Lead).delete()
            db.commit()
            print("Cleared existing leads and history.")
            existing = 0
        if existing:
            print(
                f"Database already has {existing} leads. Skipping seed. "
                "(Use --reset to clear and reseed)"
            )
            return

        for data in SAMPLE_LEADS:
            lead = Lead(**data)
            db.add(lead)
            apply_scoring(db, lead, reason="seeded")
        db.commit()

        distribution = {"Hot Lead": 0, "Warm Lead": 0, "Cold Lead": 0, "Unqualified": 0}
        for lead in db.query(Lead).order_by(Lead.score.desc()).all():
            score, _, grade = score_lead(lead)
            distribution[grade] = distribution.get(grade, 0) + 1
            print(f"  {lead.full_name:22s} | {lead.company or '':22s} | {score:3d} | {grade}")

        print(f"\nSeeded {len(SAMPLE_LEADS)} demo leads. Grades: {distribution}")
    finally:
        db.close()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Seed LeadBolt with demo leads.")
    parser.add_argument(
        "--reset", action="store_true", help="Clear existing leads and reseed"
    )
    args = parser.parse_args()
    seed(reset=args.reset)
